// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UpdateCheckResult 更新检查结果
 */
export class UpdateCheckResult {
    /**
     * Creates a new UpdateCheckResult instance.
     * @param {Partial<UpdateCheckResult>} [$$source = {}] - The source object to create the UpdateCheckResult.
     */
    constructor($$source = {}) {
        if (!("has_update" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_update"] = false;
        }
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("latest_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest_version"] = "";
        }
        if (!("release_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_url"] = "";
        }
        if (!("release_notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_notes"] = "";
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateCheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCheckResult(/** @type {Partial<UpdateCheckResult>} */($$parsedSource));
    }
}
