// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../pkg/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as arigo$0 from "../../../../github.com/siku2/arigo/models.js";

/**
 * @param {string} metalink
 * @param {arigo$0.Options | null} options
 * @returns {$CancellablePromise<arigo$0.GID[]>}
 */
export function AddMetalink(metalink, options) {
    return $Call.ByID(2685495437, metalink, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} metalink
 * @param {number} position
 * @param {arigo$0.Options | null} options
 * @returns {$CancellablePromise<arigo$0.GID[]>}
 */
export function AddMetalinkAtPosition(metalink, position, options) {
    return $Call.ByID(3567954291, metalink, position, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} torrent
 * @param {string[]} uris
 * @param {arigo$0.Options | null} options
 * @returns {$CancellablePromise<arigo$0.GID>}
 */
export function AddTorrent(torrent, uris, options) {
    return $Call.ByID(2959409914, torrent, uris, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} torrent
 * @param {string[]} uris
 * @param {number} position
 * @param {arigo$0.Options | null} options
 * @returns {$CancellablePromise<arigo$0.GID>}
 */
export function AddTorrentAtPosition(torrent, uris, position, options) {
    return $Call.ByID(495544588, torrent, uris, position, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string[]} uris
 * @param {arigo$0.Options | null} options
 * @returns {$CancellablePromise<arigo$0.GID>}
 */
export function AddURI(uris, options) {
    return $Call.ByID(209005542, uris, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string[]} uris
 * @param {number} position
 * @param {arigo$0.Options | null} options
 * @returns {$CancellablePromise<arigo$0.GID>}
 */
export function AddURIAtPosition(uris, position, options) {
    return $Call.ByID(798790192, uris, position, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {arigo$0.Options} options
 * @returns {$CancellablePromise<void>}
 */
export function ChangeGlobalOptions(options) {
    return $Call.ByID(3956864768, options);
}

/**
 * @param {string} gid
 * @param {arigo$0.Options} options
 * @returns {$CancellablePromise<void>}
 */
export function ChangeOptions(gid, options) {
    return $Call.ByID(45997989, gid, options);
}

/**
 * @param {string} gid
 * @param {number} pos
 * @param {arigo$0.PositionSetBehaviour} how
 * @returns {$CancellablePromise<number>}
 */
export function ChangePosition(gid, pos, how) {
    return $Call.ByID(1737709322, gid, pos, how);
}

/**
 * @param {string} gid
 * @param {number} fileIndex
 * @param {string[]} delURIs
 * @param {string[]} addURIs
 * @returns {$CancellablePromise<[number, number]>}
 */
export function ChangeURI(gid, fileIndex, delURIs, addURIs) {
    return $Call.ByID(1293162365, gid, fileIndex, delURIs, addURIs);
}

/**
 * @param {string} gid
 * @param {number} fileIndex
 * @param {string[]} delURIs
 * @param {string[]} addURIs
 * @param {number} position
 * @returns {$CancellablePromise<[number, number]>}
 */
export function ChangeURIAt(gid, fileIndex, delURIs, addURIs, position) {
    return $Call.ByID(3536283904, gid, fileIndex, delURIs, addURIs, position);
}

/**
 * ContinueDownload 从历史记录继续未完成的下载
 * @param {string} gid
 * @returns {$CancellablePromise<arigo$0.GID>}
 */
export function ContinueDownload(gid) {
    return $Call.ByID(1382319188, gid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function Delete(gid) {
    return $Call.ByID(218769186, gid);
}

/**
 * DeleteDownloadRecord 删除下载记录
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDownloadRecord(gid) {
    return $Call.ByID(907312311, gid);
}

/**
 * @param {string[]} uris
 * @param {arigo$0.Options | null} options
 * @returns {$CancellablePromise<arigo$0.Status>}
 */
export function Download(uris, options) {
    return $Call.ByID(1586351329, uris, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * FindDownloadByURL 根据 URL 查找已存在的下载记录（用于重复检测，返回 nil 表示无重复）
 * @param {string} url
 * @returns {$CancellablePromise<store$0.DownloadRecord | null>}
 */
export function FindDownloadByURL(url) {
    return $Call.ByID(1664448380, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function ForcePause(gid) {
    return $Call.ByID(1494990086, gid);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ForcePauseAll() {
    return $Call.ByID(4093527589);
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function ForceRemove(gid) {
    return $Call.ByID(2912107036, gid);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ForceShutdown() {
    return $Call.ByID(1401080262);
}

/**
 * GetDefaultDownloadDir 获取上次使用的下载目录（从 SQLite 读取）
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultDownloadDir() {
    return $Call.ByID(3028928127);
}

/**
 * GetDownload 获取单条下载记录
 * @param {string} gid
 * @returns {$CancellablePromise<store$0.DownloadRecord | null>}
 */
export function GetDownload(gid) {
    return $Call.ByID(826451291, gid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<arigo$0.File[]>}
 */
export function GetFiles(gid) {
    return $Call.ByID(3555216470, gid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<arigo$0.GID>}
 */
export function GetGID(gid) {
    return $Call.ByID(1711397861, gid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<arigo$0.Options>}
 */
export function GetGlobalOptions() {
    return $Call.ByID(887462282).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<arigo$0.Stats>}
 */
export function GetGlobalStats() {
    return $Call.ByID(640655199).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<arigo$0.Options>}
 */
export function GetOptions(gid) {
    return $Call.ByID(2924744555, gid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<arigo$0.Peer[]>}
 */
export function GetPeers(gid) {
    return $Call.ByID(3707403540, gid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<arigo$0.FileServers[]>}
 */
export function GetServers(gid) {
    return $Call.ByID(1945979029, gid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<arigo$0.SessionInfo>}
 */
export function GetSessionInfo() {
    return $Call.ByID(3060104193).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetSettings 获取用户设置（从 SQLite 读取，未设置的返回默认值）
 * @returns {$CancellablePromise<store$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(2427175778).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<arigo$0.URI[]>}
 */
export function GetURIs(gid) {
    return $Call.ByID(822278332, gid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @returns {$CancellablePromise<arigo$0.VersionInfo>}
 */
export function GetVersion() {
    return $Call.ByID(1619621777).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * ListDownloads 分页查询下载记录，status为空时返回全部
 * @param {string} status
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<[store$0.DownloadRecord[], number]>}
 */
export function ListDownloads(status, offset, limit) {
    return $Call.ByID(3170557266, status, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType19($result[0]);
        return $result;
    }));
}

/**
 * ListEventsByGID 获取指定下载任务的事件记录
 * @param {string} gid
 * @returns {$CancellablePromise<store$0.EventRecord[]>}
 */
export function ListEventsByGID(gid) {
    return $Call.ByID(2255594963, gid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {arigo$0.MethodCall | null[]} methods
 * @returns {$CancellablePromise<arigo$0.MethodResult[]>}
 */
export function MultiCall(...methods) {
    return $Call.ByID(1879961790, methods).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function Pause(gid) {
    return $Call.ByID(3127631333, gid);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PauseAll() {
    return $Call.ByID(3340569540);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PurgeDownloadResults() {
    return $Call.ByID(1072719690);
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function Remove(gid) {
    return $Call.ByID(2855282117, gid);
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function RemoveDownloadResult(gid) {
    return $Call.ByID(1997025144, gid);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SaveSession() {
    return $Call.ByID(1335241884);
}

/**
 * SaveSettings 保存用户设置到 SQLite 并同步到 aria2
 * @param {store$0.Settings | null} s
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(s) {
    return $Call.ByID(1598019101, s);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(4287858883);
}

/**
 * @param {arigo$0.EventType} evtType
 * @param {arigo$0.EventListener} listener
 * @returns {$CancellablePromise<arigo$0.UnsubscribeFunc>}
 */
export function Subscribe(evtType, listener) {
    return $Call.ByID(2983506987, evtType, listener);
}

/**
 * @param {string[]} keys
 * @returns {$CancellablePromise<arigo$0.Status[]>}
 */
export function TellActive(...keys) {
    return $Call.ByID(3030015388, keys).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @param {string} gid
 * @param {string[]} keys
 * @returns {$CancellablePromise<arigo$0.Status>}
 */
export function TellStatus(gid, ...keys) {
    return $Call.ByID(2921941524, gid, keys).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} offset
 * @param {number} num
 * @param {string[]} keys
 * @returns {$CancellablePromise<arigo$0.Status[]>}
 */
export function TellStopped(offset, num, ...keys) {
    return $Call.ByID(454591527, offset, num, keys).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @param {number} offset
 * @param {number} num
 * @param {string[]} keys
 * @returns {$CancellablePromise<arigo$0.Status[]>}
 */
export function TellWaiting(offset, num, ...keys) {
    return $Call.ByID(542714025, offset, num, keys).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function Unpause(gid) {
    return $Call.ByID(2390240532, gid);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UnpauseAll() {
    return $Call.ByID(3906551215);
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function WaitForDownload(gid) {
    return $Call.ByID(2786311923, gid);
}

// Private type creation functions
const $$createType0 = arigo$0.GID.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = arigo$0.Status.createFrom;
const $$createType3 = store$0.DownloadRecord.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = arigo$0.File.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = arigo$0.Options.createFrom;
const $$createType8 = arigo$0.Stats.createFrom;
const $$createType9 = arigo$0.Peer.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = arigo$0.FileServers.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = arigo$0.SessionInfo.createFrom;
const $$createType14 = store$0.Settings.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = arigo$0.URI.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = arigo$0.VersionInfo.createFrom;
const $$createType19 = $Create.Array($$createType3);
const $$createType20 = store$0.EventRecord.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = arigo$0.MethodResult.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = $Create.Array($$createType2);
