// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    BitTorrentStatus,
    BitTorrentStatusInfo,
    DownloadStatus,
    EventType,
    ExitStatus,
    File,
    FileServers,
    GID,
    MethodCall,
    MethodResult,
    Options,
    Peer,
    PositionSetBehaviour,
    Server,
    SessionInfo,
    Stats,
    Status,
    TorrentMode,
    URI,
    URIStatus,
    VersionInfo
} from "./models.js";

import * as $models from "./models.js";

/**
 * EventListener represents a function which should be called
 * when an event occurs.
 * @typedef {$models.EventListener} EventListener
 */

/**
 * UNIXTime is a wrapper around time.Time that marshals to a unix timestamp.
 * @typedef {$models.UNIXTime} UNIXTime
 */

/**
 * UnsubscribeFunc is a function which when called, unsubscribes from an
 * event.
 * @typedef {$models.UnsubscribeFunc} UnsubscribeFunc
 */
