// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GID provides an object oriented approach to arigo.
 * Instead of calling the methods on the client directly,
 * you can call them on the GID instance.
 */
export class GID {
    /**
     * Creates a new GID instance.
     * @param {Partial<GID>} [$$source = {}] - The source object to create the GID.
     */
    constructor($$source = {}) {
        if (!("GID" in $$source)) {
            /**
             * gid of the download
             * @member
             * @type {string}
             */
            this["GID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GID instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GID}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GID(/** @type {Partial<GID>} */($$parsedSource));
    }
}

/**
 * Options represents the aria2 input file options
 */
export class Options {
    /**
     * Creates a new Options instance.
     * @param {Partial<Options>} [$$source = {}] - The source object to create the Options.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["all-proxy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["all-proxy-passwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["all-proxy-user"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["allow-overwrite"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["allow-piece-length-change"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["always-resume"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["async-dns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["auto-file-renaming"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["bt-enable-hook-after-hash-check"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["bt-enable-lpd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bt-exclude-tracker"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bt-external-ip"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["bt-force-encryption"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["bt-hash-check-seed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["bt-load-saved-metadata"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["bt-max-peers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["bt-metadata-only"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bt-min-crypto-level"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bt-prioritize-piece"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["bt-remove-unselected-file"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bt-request-peer-speed-limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["bt-require-crypto"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["bt-save-metadata"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["bt-seed-unverified"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["bt-stop-timeout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bt-tracker"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["bt-tracker-connect-timeout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["bt-tracker-interval"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["bt-tracker-timeout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["check-integrity"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["checksum"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["conditional-get"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["connect-timeout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["content-disposition-default-utf8"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["continue"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["dry-run"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["enable-http-keep-alive"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["enable-http-pipelining"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["enable-mmap"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["enable-peer-exchange"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["file-allocation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["follow-metalink"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["follow-torrent"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["force-save"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ftp-passwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["ftp-pasv"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ftp-proxy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ftp-proxy-passwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ftp-proxy-user"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["ftp-reuse-connection"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ftp-type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ftp-user"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["gid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["hash-check-only"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["header"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["http-accept-gzip"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["http-auth-challenge"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["http-no-cache"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["http-passwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["http-proxy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["http-proxy-passwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["http-proxy-user"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["http-user"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["https-proxy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["https-proxy-passwd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["https-proxy-user"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["index-out"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lowest-speed-limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["max-concurrent-downloads"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["max-connection-per-server"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["max-download-limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["max-file-not-found"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["max-mmap-limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["max-resume-failure-tries"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["max-tries"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["max-upload-limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["metalink-base-uri"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["metalink-enable-unique-protocol"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["metalink-language"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["metalink-location"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["metalink-os"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["metalink-preferred-protocol"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["metalink-version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["min-split-size"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["no-file-allocation-limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["no-netrc"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["no-proxy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["out"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parameterized-uri"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["pause"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["pause-metadata"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["piece-length"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["proxy-method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["realtime-chunk-checksum"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["referer"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["remote-time"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remove-control-file"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["retry-wait"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["reuse-uri"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rpc-save-upload-metadata"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["seed-ratio"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["seed-time"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["select-file"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["split"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ssh-host-key-md"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["stream-piece-selector"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${number}` | undefined}
             */
            this["timeout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["uri-selector"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {`${boolean}` | undefined}
             */
            this["use-head"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["user-agent"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Options}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Options(/** @type {Partial<Options>} */($$parsedSource));
    }
}
