// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as v1$0 from "../../../../../changeme/backed/api/apiserver/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as sys$0 from "../../../../../changeme/backed/internal/apiserver/controller/v1/sys/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "download-removed": string;
            "download-update": v1$0.DownloadRecord;
            "time": string;
            "tray-new-task": string;
            "update-check": sys$0.UpdateCheckResult;
        }
    }
}
