// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as store$0 from "../../../../../changeme/backed/pkg/store/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "download-removed": string;
            "download-update": store$0.DownloadRecord;
            "time": string;
        }
    }
}
