// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../api/apiserver/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sys$0 from "../../apiserver/controller/v1/sys/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as arigo$0 from "../../../../../github.com/siku2/arigo/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string[]} uris
 * @param {arigo$0.Options | null} options
 * @returns {$CancellablePromise<arigo$0.GID>}
 */
export function AddURI(uris, options) {
    return $Call.ByID(735356118, uris, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<sys$0.UpdateCheckResult | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2713876947).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.CompletedConfig>}
 */
export function Complete() {
    return $Call.ByID(2333430474).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<arigo$0.GID>}
 */
export function ContinueDownload(gid) {
    return $Call.ByID(3487578340, gid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDownloadRecord(gid) {
    return $Call.ByID(4189744999, gid);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<v1$0.DownloadRecord | null>}
 */
export function FindDownloadByURL(url) {
    return $Call.ByID(1628606092, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(3701850838);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultDownloadDir() {
    return $Call.ByID(3350825199);
}

/**
 * @returns {$CancellablePromise<v1$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(2052809874).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} status
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<[v1$0.DownloadRecord[], number]>}
 */
export function ListDownloads(status, offset, limit) {
    return $Call.ByID(3805255138, status, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType8($result[0]);
        return $result;
    }));
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function Pause(gid) {
    return $Call.ByID(4073903125, gid);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PurgeDownloadResults() {
    return $Call.ByID(957227610);
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function Remove(gid) {
    return $Call.ByID(2495858741, gid);
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function RemoveDownloadResult(gid) {
    return $Call.ByID(2373465864, gid);
}

/**
 * @param {v1$0.Settings | null} st
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(st) {
    return $Call.ByID(2719101517, st);
}

/**
 * @param {string} gid
 * @returns {$CancellablePromise<void>}
 */
export function Unpause(gid) {
    return $Call.ByID(2664808420, gid);
}

// Private type creation functions
const $$createType0 = arigo$0.GID.createFrom;
const $$createType1 = sys$0.UpdateCheckResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.CompletedConfig.createFrom;
const $$createType4 = v1$0.DownloadRecord.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = v1$0.Settings.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType4);
