// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CompletedConfig {
    /**
     * Creates a new CompletedConfig instance.
     * @param {Partial<CompletedConfig>} [$$source = {}] - The source object to create the CompletedConfig.
     */
    constructor($$source = {}) {
        if (!("RpcPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RpcPort"] = "";
        }
        if (!("Endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Endpoint"] = "";
        }
        if (!("RpcSecret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RpcSecret"] = "";
        }
        if (!("SessionPath" in $$source)) {
            /**
             * api session 文件路径（保存/恢复下载进度）
             * @member
             * @type {string}
             */
            this["SessionPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompletedConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompletedConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompletedConfig(/** @type {Partial<CompletedConfig>} */($$parsedSource));
    }
}
