// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * DownloadRecord 表示一条下载记录
 */
export class DownloadRecord {
    /**
     * Creates a new DownloadRecord instance.
     * @param {Partial<DownloadRecord>} [$$source = {}] - The source object to create the DownloadRecord.
     */
    constructor($$source = {}) {
        if (!("gid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gid"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("total_length" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_length"] = 0;
        }
        if (!("completed_length" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completed_length"] = 0;
        }
        if (!("download_speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["download_speed"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("error_code" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["error_code"] = 0;
        }
        if (!("error_message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error_message"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["completed_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadRecord(/** @type {Partial<DownloadRecord>} */($$parsedSource));
    }
}

/**
 * Settings 表示用户可配置的设置项
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("default_download_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default_download_dir"] = "";
        }
        if (!("max_concurrent_downloads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_concurrent_downloads"] = 0;
        }
        if (!("max_connection_per_server" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_connection_per_server"] = 0;
        }
        if (!("split" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["split"] = 0;
        }
        if (!("max_download_limit" in $$source)) {
            /**
             * bytes/s, 0=不限速
             * @member
             * @type {number}
             */
            this["max_download_limit"] = 0;
        }
        if (!("continue_download" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["continue_download"] = false;
        }
        if (!("allow_overwrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allow_overwrite"] = false;
        }
        if (!("auto_file_renaming" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_file_renaming"] = false;
        }
        if (!("auto_check_update" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_check_update"] = false;
        }
        if (!("auto_start_unfinished" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_start_unfinished"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}
