// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as arigo$0 from "../../../../github.com/siku2/arigo/models.js";

/**
 * @param {string[]} uris
 * @param {arigo$0.Options | null} options
 * @returns {$CancellablePromise<arigo$0.GID>}
 */
export function AddURI(uris, options) {
    return $Call.ByID(2852672615, uris, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PauseAll() {
    return $Call.ByID(1031966029);
}

// Private type creation functions
const $$createType0 = arigo$0.GID.createFrom;
